### ISSUE TITLE
[Feature] Release X units proportionally

### ISSUE THREAD

**Issue by CjHare** [windranger-io/windranger-treasury#60]
## Feature Description

Release a subset of a bond's collateral, with the remaining amount staying in the bond.

This is a partial release, difference with a partial slashing being the collateral staying in the bond rather than being moved to the Treasury.

## Additional Information

*WARNING* Implementing this introduces a scalability risk.

To release proportions means introducing a mapping for allowed withdrawals (`mapping(address=>uint256)`), with the first proportional release having to populate (and pay for) the storage allocation of allowed withdrawals. 
A linear growth cost i.e.
```
  cost = tx_base + number_of_guarantors * uint256_storage_cost
```
The `tx_base` being the base transaction cost and any non-repeating computation.

At some number of guarantors the cost would exceed the gas limit for a block. That's likely to be a very large number ...but it does exist, with this feature adding the scalability limitation.

**Comment by CjHare** [comment]
> proportional release could be a bit tricky as its not quite the mechanics of Uni v2 LP tokens (as release is only when you redeem the receipt LP token), or Sushi rewarder Onsen mechanics which is per block rewards assigned to your key. Maybe to utilize those battletested mechanics we do it like this:
Redemption of receipt token will take proportional share of what ever is in the pool (post slashing and rewards, similar to Uni LP mechanics)
Proportional release will be a special "slashing" of the pool, where assets go to a "claim bucket", snapshotted against eligible bonders during the time. similar to Onsen/sushi rewarder contracts.
To avoid too many micro deposits we probably need another field which is "minimum bond" parameter.

**Comment by qubitcrypto** [comment]
Question: is the following logic expected and correct?

In a simple scenario where this is only ONE user purchasing the bonds with BIT:

1. User sends 100 BIT, the contract takes it and issues him 100 BOND (the ERC20 token of this contract);
2. Users sends 100, 100, 100, 100 BIT in a row, now the collateral is 500 BIT, user get 500 BOND;
3. Now we slash 50 BIT;
4. We partial release 75 BIT back to the pool;
5. We slash 50 BIT again;
6. We release 75 BIT again;
7. Now we open the redemption;

Using the 500 BOND the user still holds, he can redeem 500 - (50+75+50+75) = 250 BIT

The user can withdraw 75 + 75 = 150 BIT due to the "partial release" back to the pool.

Is the above computation what we want?

If yes the a simple solution seems to be:

1. Create a total_deposit variable to track the total_deposit 
1. Use a map to track each user's bond payment;
2. Keep a running _collateral that will be reduced each time a "slash" AND "partial release" happens;
3. Keep a running _partial_release_total that increment with each partial release;
4. Create a withdraw function for withdrawing partial release, withdrawal_amount = user_total_deposit * partial_release_total / total_deposit

The above solution depends on allowing withdrawal after allowing redemption, so all the slashes and partial releases are already done by the admin, which seems logical to me, so user can withdraw the partial release at one shot.

Please share more insights so we can implement it.

**Comment by CjHare** [comment]
As Bond debt tokens are tradable, that also needs supporting & testing.

**Comment by CjHare** [comment]
>  There are two main scenario that spring to mind:
Product creation/delivery; a boolean achievement, as you either have the fully featured product delivered to match the performance criterion, or you do not (As the saying goes, the first 80% of the project takes 80% of the time …the next 20% takes another 80% of the time :grinning:).
Achievement metric: a tangible measurable target is given and only partially achieved, here the expectation is the target would be fully realised given more time e.g. sign up ten users in two months, but only 7 are signed up by the evaluation date.
Really it comes down to the idea and chosen application of Performance Bonds, specifically on criterion evaluation.
If we have performance criterion evaluated on a specific date, they will either be fully met, partially met or not at all satisfied, which if enforced as is, equates to fFull redemption, partially slashed, or fully slashed.
The case for partial release could be point two, when the collateral is considerable, there could be milestone releases ….but that could also be implemented by using multiple bonds, a separate bond. for each milestone :thinking_face:

**Comment by CjHare** [comment]
I feel that multiple successive bonds would be a better use of the platform than one large bond with long term performance criteria on a single evaluation date

For that reason I lean towards not having partial release. We should encourage any complex projects to begin with a roadmap of staggered bonds. From this we can see if new scenarios appear through use of the platform and we use that to evaluate adding a partial release feature

**Comment by CjHare** [comment]
> Yeh probably staggered bonds (and funding requests) would be the approach

**Comment by CjHare** [comment]
Above comments are from thread discussing implementing a partial release using staggered bonds, instead of a single with proportional release.

Achieves the same outcome, but without bloating the gas cost of all other use cases.
